-- ROW NUMBER()
	-- Returns record numbers 
	-- Row_number is also based on one or more columns 
	-- For row_number also data must be stored

-- DISPLAY ROW NUMBERS BASED ON SAL?
SELECT EMPNO,ENAME,SAL,
ROW_NUMBER() OVER (ORDER BY SAL DESC) AS RNO FROM EMP

-- ROW NUMBERS BASED ON EMPNO ?
SELECT EMPNO,ENAME,SAL,
ROW_NUMBER() OVER (ORDER BY EMPNO ASC) AS RNO FROM EMP

-- ABOVE QUERY DISPLAYS ALL RECORDS WITH ROW NUMBERS BUT TO DISPLAY 5 FIRST ROWS
WITH E AS 
(SELECT EMPNO,ENAME,SAL,
ROW_NUMBER() OVER (ORDER BY EMPNO ASC) AS RNO FROM EMP)
SELECT* FROM E WHERE RNO<=5






CREATE TABLE EMP44
(
ENO INT,
ENAME VARCHAR(10),
SAL MONEY
)

INSERT INTO EMP44 VALUES
(1,'A',5000),(2,'B',6000),(3,'C',7000),(1,'A',5000),(2,'B',6000)

--STEP 1 :- Generate row_numbers with in the partition of eno,ename,sal
SELECT ENO,ENAME,SAL,
ROW_NUMBER() OVER (PARTITION BY ENO,ENAME,SAL ORDER BY ENO ASC) AS RNO FROM EMP44


--STEP 2 :- Delete the records with row_number > 1
WITH E AS
(
SELECT ENO,ENAME,SAL,
ROW_NUMBER() OVER (PARTITION BY ENO,ENAME,SAL ORDER BY ENO ASC) AS RNO
FROM EMP44
)
DELETE FROM E WHERE RNO>1

SELECT * FROM EMP44

