USE DB7AM
SELECT * FROM SALES

SP_HELP SALES

-- WHEN WE TAKE CSV FILE DIRECTLY EVERY DATATYPE IS VARCHAR.

-- COMMANDS TO CHANGE THE DATATYPES  (CHANGE ANY COLUMN DATATYPE)
ALTER TABLE SALES ALTER COLUMN SALES MONEY


-- DISPLAY REGION WISE TOTAL SALES?
SELECT REGION, SUM(SALES) AS TOTAL_AMOUNT
FROM SALES
GROUP BY REGION

-- DISPLAY REGION WISE AND WITH IN REGION CATEGORY WISE TOTAL AMOUNT?
SELECT REGION,CATEGORY,SUM (SALES) AS TOTAL_AMOUNT
FROM SALES 
GROUP BY REGION ,CATEGORY 
ORDER BY REGION ASC

-- DISPLAY REGION WISE,STATE WISE, CATEGORY WISE TOTAL AMOUNT?
SELECT REGION,STATE,CATEGORY, SUM (SALES) AS TOTAL_AMOUNT
FROM SALES 
GROUP BY REGION,STATE,CATEGORY
ORDER BY REGION ASC,STATE ASC